### ISSUE TITLE
Upstream Wine-8.x is borked / Modern Wine builds are NOT suitable for my use.

### ISSUE THREAD

**Issue by nine7nine** [nine7nine/Wine-NSPA#6]
Wine-8.x is junk.

Not suitable for my use case of proaudio, in general. why?

- significantly higher CPU usage vs. Wine-7.5 (and below) like a solid 10-15% higher in most cases.
- Periodic Stalling. ~ I've ruled out my patches and also Fsync. It looks like it is caused somewhere in the heap / memory code. (not something i can resolve or fix). 

I am going to continue to rebase and periodically test, but atm, upstream Wine is just awful for performance. Definitely not suitable to be using for my own use-case (ie: using Ableton Live, or even NI Komplete 13 on it's own)... it's sad that after 15 years I can't seem to use my software on the latest / a modern version of wine...

For now, I'm using Windows... When i'm not as busy with work: I'm going to go back and do a clean rebase / build of Wine-NSPA-7.5, basically from scratch to clean out some cruft and re-organize patchwork. (solely for use with Yabridge and/or Element)

The future of using Wine doesn't look bright though - I've waited months for Wine-8.x to deliver and it's still utter crap, all around. (if you actually care about getting relatively decent performance, anyway).

**Comment by revast** [comment]
Sad to hear that, hopefully this will get sorted out. 
Thanks for your tremendous work so far ! - following eagerly.
Is there something to do, like filing/pushing bug reports @upstream Wine/Proton ?

**Comment by nine7nine** [comment]
@revast 

oh, I'm sure it'll all get worked out. but it's one of those things: I don't have a tonne of time and it's an upstream problem.

there has been heavy churn of changes and workings to Wine - all of PE work. LHF work, etc... I'm not surprised things are a bit borked, atm... I'm sure it'll all get ironed out and I'll be able to use WIne again...

but for now: I'm more focused on other things... and I do plan on reworking my 7.5 builds soon - dropping some code, updating some other bits and just getting it back to being ideal for my primary use case. (mainly, for YaBridge + NI + UHE, etc && to use Kushview Element, as well).

I'll probably push a cleaned up, stripped down and updated version of Wine-7.5+ in the next month or so. As soon as my free time permits

**Comment by nine7nine** [comment]
huh,

well, it looks like upstream wine has fixed some of the (big) issues that we show-blocking bugs / problems...

i just rebased on Wine-Staging -- and, in particular, the synchronization and audio issues have gone away...

i m getting some lock contention and some other instability -- but with the above seemingly resolved, it mans i can probably look at trying to stabilize Wine-NSPA-8.x in the coming week or so...

**Comment by nine7nine** [comment]
no longer borked... closing ;-)

- 8.x builds still need some testing, but most likely they will replace 7.5 builds very soon
