### ISSUE TITLE
no luck so far with 7x and 8x wine-nspa branch

### ISSUE THREAD

**Issue by revast** [nine7nine/Wine-NSPA#9]
I managed to compile 8x, 
but it fails to launch currently:

```
export WINEDLLOVERRIDES="mscoree,mshtml=" 
export WINEDLLOVERRIDES=winemenubuilder.exe=d   
export WINEFSYNC=1 
WINEPREFIX=/home/mero/wine-base winecfg 
wine: created the configuration directory '/home/hero/wine-base' 
fsync: up and running. 
Fatal glibc error: allocatestack.c:333 (allocate_stack): assertion failed: size != 0 
^CTerminated
```

and with 7x, a patch is sadly not merging:
```

  -> Applying josh-flat-theme.patch
  -> ## Applying hotfix for plain-wine: Return_nt_filename_and_resolve_DOS_drive_path.mypatch
  -> ## Applying hotfix for plain-wine: ef6e33f.mypatch
  -> ## Applying hotfix for plain-wine: 0001-proton-bcrypt_rdr2_fixes4.mypatch
==> ERROR: Patch application has failed. The error was logged to /home/hero/Wine-NSPA2/Wine-NSPA/Wine-NSPA/wine-nspa-7x-git/prepare.log for your convenience.
  -> Removed BIG_UGLY_FROGMINER - Ribbit
  -> Removed Proton-tkg token - Valve Ribbit
  -> exit cleanup done


```

this is with linux-nspa kernel running, but no optimization otherwise done to the os - running in virtualbox

**Comment by nine7nine** [comment]
Running in a virtualized environment is a no-go. it may be possible with KVM and hardware passthrough, but with Virtualbox - definitely not... Also, I do not maintain 7x anymore

* Can I see your systemd configs? (eg: /etc/systemd/system.conf & user.conf)

**Comment by Shnalf** [comment]
I could reproduce the error for 8x (on a physical machine) by not having the environment variables defined in /etc/environment. It occurred to me, when I was trying to define them in my ~/.bashrc instead.

**Comment by nine7nine** [comment]
@Shnalf  - Thanks for pointing this detail out. I guess @revast was likely doing something similar (?).

I make my wine env variables system-wide, and it's also what i recommend. Probably the only exception to that might be WINEPREFIX+ if using multiple prefixes. In that case, I would probably not have it set globally. (But I only use one wine prefix, personally).

**Comment by nine7nine** [comment]
@revast -I'm closing this error -- It seems you were manually trying to set env variables, rather than using them in /etc/environment as I do / suggest... and also: I've archived 7x code, as it doesn't build and I have no intention of fixing that...

@Shnalf - thanks again for pointing out the issue
